### ISSUE TITLE
[REQUEST] Config file settings + functions

### ISSUE THREAD

**Issue by eliweitzman** [eliweitzman/EnterpriseTechTool#24]
**Describe the solution you'd like**

A settings UX, which allows for feature flags to be turned on or off, baked into the main UX. Allows customizations to be saved locally and without needing to remanufacture and recompile ETT with custom changes. 

**Describe alternatives you've considered**
Keeping as-is with feature flags and conditionality

**Comment by eliweitzman** [comment]
Pushing to 1.2.1

**Comment by TheDeadGPU** [comment]
I kinda got this working by creating a config.ini file with the contents 

```
function MyFunction { Write-Host 'Hello from MyFunction!'}
function MyFunction2 { Write-Host 'Hello from MyFunction2!'}
```

Then the functions get read in with the following PowerShell code

```
$content = Get-Content .\config.ini -Raw
. { Invoke-Expression "$content" }
MyFunction
MyFunction2
```

**Comment by TheDeadGPU** [comment]
![image](https://github.com/eliweitzman/EnterpriseTechTool/assets/12623002/914dfdb3-6aab-4e0a-abbf-20ab2944fe2d)

**Comment by TheDeadGPU** [comment]
There is still more work to be done on this Feature Request. Going to leave this open for now.

**Comment by TheDeadGPU** [comment]
I'm thinking we can do something where we can define which tab a custom function can go under if we don't want it under the custom tab. Maybe have the function naming schema be "tabname_custom_nameoffunction"? What are your thoughts @eliweitzman?

**Comment by TheDeadGPU** [comment]
Just need to implement the function description on list item hover and then we can close.

**Comment by eliweitzman** [comment]
> I'm thinking we can do something where we can define which tab a custom function can go under if we don't want it under the custom tab. Maybe have the function naming schema be "tabname_custom_nameoffunction" or "custom_tabname_nameoffunction"? What are your thoughts @eliweitzman?

I like this naming style! The only issue being it might things a bit more complex when it comes to differentiating proprietary and custom functions from existing ones... Unless maybe we add some sort of a differentiating symbol that could point out custom from built-in... The only idea being to keep a visible separation for any future variants.

**Comment by eliweitzman** [comment]
Also, I'm seeing a new error it looks like in how we're taking in custom functions from the config file... 

```
You cannot call a method on a null-valued expression.

+ $Tab5.Controls.Add($ADList)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```

**Comment by TheDeadGPU** [comment]
This is done.
