### ISSUE TITLE
[ENHANCEMENT] Windows Update Check (Expanded)

### ISSUE THREAD

**Issue by eliweitzman** [eliweitzman/EnterpriseTechTool#54]
Expand Windows Update Check to become actionable, with an addition to the pop-up for Windows Update Check, prompting to proceed with Updates IF the Windows Update check finds updates, using the Windows.Update.Session API

[References: https://learn.microsoft.com/en-us/windows/win32/wua_sdk/searching--downloading--and-installing-specific-updates](https://learn.microsoft.com/en-us/windows/win32/wua_sdk/searching--downloading--and-installing-specific-updates)

**Comment by eliweitzman** [comment]
This was added in https://github.com/eliweitzman/EnterpriseTechTool/commit/3fca413721b0b4852346ae9b2d0c1ef2e0bd85cd - shifting to testing needed

**Comment by eliweitzman** [comment]
> Need to fix the way updates are displayed to the GUI. Notes below.

PS C:\WINDOWS\system32> $searchresult.Updates.Title
PS C:\WINDOWS\system32> $searchresult.Updates[0].Title
Security Intelligence Update for Microsoft Defender Antivirus - KB2267602 (Version 1.403.870.0) - Current Channel (Broad)
PS C:\WINDOWS\system32> $searchresult.Updates.length
PS C:\WINDOWS\system32> $searchresult.Updates.count
1

@TheDeadGPU

**Comment by TheDeadGPU** [comment]
All we need to do now is add the logic for user consent to install updates since it is just automatic right now. Need to segment for Admin / Non Admin mode. Also need to isolate the function to a separate process.

**Comment by eliweitzman** [comment]
Going to try and clean this up tonight, so we can kick off the PR and approvals stage!

**Comment by TheDeadGPU** [comment]
Going to leave this here for the future.

https://gist.github.com/srz-zumix/f8192335b12ee6c51ef702defc51e554

**Comment by eliweitzman** [comment]
Now need to just test the logic for new windows update selections.

**Comment by eliweitzman** [comment]
Tested, and fixed more of the logic. This is ready to roll!
