### ISSUE TITLE
[REQUEST] Add Battery Diagnostics Button

### ISSUE THREAD

**Issue by TheDeadGPU** [eliweitzman/EnterpriseTechTool#61]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A button that launches the Windows Battery Diagnostics.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by eliweitzman** [comment]
Implemented, with additional logic on the backend to validate that the battery diagnostic only runs on laptops, not desktops or other devices...

**Comment by eliweitzman** [comment]
Added support, and cleaned up further in https://github.com/eliweitzman/EnterpriseTechTool/commit/b94d17847606f853517c5e6a1cfdf3a4665abf45 for more device types. Slates (tablets), and appliance PCs are now allowed to bypass the devicetype restriction (I figured both might be ideal as well)

**Comment by TheDeadGPU** [comment]
Need to fix the way updates are displayed to the GUI. Notes below.

PS C:\WINDOWS\system32> $searchresult.Updates.Title
PS C:\WINDOWS\system32> $searchresult.Updates[0].Title
Security Intelligence Update for Microsoft Defender Antivirus - KB2267602 (Version 1.403.870.0) - Current Channel (Broad)
PS C:\WINDOWS\system32> $searchresult.Updates.length
PS C:\WINDOWS\system32> $searchresult.Updates.count
1

**Comment by eliweitzman** [comment]
This is ready to ship! Closing it out for now.
