### ISSUE TITLE
[FEATURE] Custom Functions Library

### ISSUE THREAD

**Issue by eliweitzman** [eliweitzman/EnterpriseTechTool#68]
**Is your feature request related to a problem? Please describe.**
A method of adding custom functions to ETT that are limited to only my use case

**Describe the solution you'd like**
A library or menu (potentially within the toolbox) to add custom PowerShell functions and scripts.

**Comment by eliweitzman** [comment]
Figured out how to work this, which is kinda clever. Basically, it will recognize any functions with the name prefix "custom_" and add it to a list. Then, it can invoke it within.

**Comment by eliweitzman** [comment]
Want to enhance this by cleaning up the name displayed (dropping "_custom" from the front")

**Comment by TheDeadGPU** [comment]
Custom names are available for Config File Defined Custom Functions. Refer to commit 4e2c577 for more information on how this works.
