### ISSUE TITLE
[BUG] 1.3 - AD Tools tab doesn't appear in standard mode

### ISSUE THREAD

**Issue by TheDeadGPU** [eliweitzman/EnterpriseTechTool#77]
**Describe the bug**
The AD Tools tab doesn't display to the user if they are running in standard mode

**To Reproduce**
1. Open VS Code
2. Run ./ETT.ps1 from the VSCode terminal as a standard user
3. The following error will display
![image](https://github.com/eliweitzman/EnterpriseTechTool/assets/12623002/f2a36795-40ed-4a42-8712-08c618a94e72)

**Expected behavior**
The AD Tools tab should appear in standard user mode.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
- OS Version: 22H2

**Additional context**
None

**Comment by eliweitzman** [comment]
I figured out a bit with this... I think I opened a ticket or commented about this somewhere...

**Comment by eliweitzman** [comment]
Ah the latest commit was a bit on this... started working on it a bit. Looks like we have to segment how we check for RSAT installation state (one as admin, one not) since the current way really lags the loading time.

**Comment by eliweitzman** [comment]
Peep https://github.com/eliweitzman/EnterpriseTechTool/commit/5ce3e19ee86a616034baefa10b67a2b62d01dc1b

**Comment by TheDeadGPU** [comment]
Reopening because this only works when launched from VSCode. I need to figure out why the RSAT detection doesn't work when the script is compiled with ps2exe.

**Comment by eliweitzman** [comment]
Reopening...  Currently getting an error on an x64 Windows Machine - it looks like maybe our validation method might need tweaks for non-AD joined devices...

<img width="689" alt="image" src="https://github.com/eliweitzman/EnterpriseTechTool/assets/22529819/35abf205-286d-4f91-84f9-99100d123b39">

**Comment by eliweitzman** [comment]
Actually I wonder if we can resolve this with error suppressing

**Comment by eliweitzman** [comment]
Looks like some minor error suppression did the trick. Closing this again.
