### ISSUE TITLE
[IDEA] Settings Graphical UI

### ISSUE THREAD

**Issue by eliweitzman** [eliweitzman/EnterpriseTechTool#81]
**Describe the solution you'd like**
Create a graphical interface for the ETT Settings config file

**Comment by eliweitzman** [comment]
First pass completed and deployed! Moving to testing-needed.

**Comment by eliweitzman** [comment]
Also- adding to 1.3 release

**Comment by eliweitzman** [comment]
Validation Testing Needed:
IS the config file the same before and after a setting is updated?

**Comment by TheDeadGPU** [comment]
I would say that if a setting is changed, we prompt the user to restart ETT to load in the new settings. I don't see technicians constantly changing settings to the point that we would need to load them back in in real time.Thats just my two cents tho.

**Comment by eliweitzman** [comment]
> I would say that if a setting is changed, we prompt the user to restart ETT to load in the new settings. I don't see technicians constantly changing settings to the point that we would need to load them back in in real time.Thats just my two cents tho.

For sure! This is currently the implemented flow - and is probably the best way to go anyway given the current PS limitations (we can't do a hot reload easily with the way ETT currently functions as an EXE or PS1).

**Comment by eliweitzman** [comment]
Fixed a few bugs, and we now have a fully-functional settings picker. In addition, there is a new JSON-only control, which enables and disables the user's ability to open the Settings GUI editor (in the off-chance you might want to lock the config due to it living in a shared-use scenario).

**Comment by eliweitzman** [comment]
This is probably good to go now - leaving this open for review prior to launch

**Comment by eliweitzman** [comment]
Found a bug - some values are returned to the JSON config in quotes, when originally not. Working on resolving now.

**Comment by eliweitzman** [comment]
Some embedded casting was added, and we should be clear now.

**Comment by eliweitzman** [comment]
closing this out
