### ISSUE TITLE
1.3 QA Testing

### ISSUE THREAD

**Issue by eliweitzman** [eliweitzman/EnterpriseTechTool#89]
I think we're officially ready to start QA Testing ETT 1.3! All major issues and features have been implemented so far for the 1.3 build, so on to QA!

I'm opening this thread to start tracking any bugs that creep up, as well as note any other concerns/changes.

1.3 Features released:

- [x] #71 
- [x] #67 
- [x] #73 
- [x] #58 
- [x] #24 
- [x] #68 
- [x] #64 
- [x] #78 
- [x] #76 
- [x] #63 
- [x] #81 

Once tested, check the box to affirm functionality

**Comment by eliweitzman** [comment]
Fixed a bug related to #73 - some of the implementations were buggy or missing.

**Comment by eliweitzman** [comment]
Fixed a bug related to logical validation issues with update checking. Update checking can now be disabled within the config file correctly (issue using a '=' when it should be '-eq')

**Comment by eliweitzman** [comment]
Ok I think I've tested everything, but now going to compile another developer build to test

**Comment by eliweitzman** [comment]
![image](https://github.com/eliweitzman/EnterpriseTechTool/assets/22529819/21bc559b-72b8-4ca8-a60d-da62b5beb724)

**Comment by eliweitzman** [comment]
Fixed that issue - when I implemented defender ATP checking, I forgot to add it to the config file generation template. Fixed!

**Comment by eliweitzman** [comment]
Going to do one more dogfood test, before I'm in confidence to start release prep!

**Comment by eliweitzman** [comment]
Still in dogfooding... and ended up getting sidetracked. But soon!

**Comment by TheDeadGPU** [comment]
We're ready. Sorry for the delay but its worth it! 

![image](https://github.com/user-attachments/assets/fd378a14-3599-4de1-b67e-9202c99253b7)

**Comment by eliweitzman** [comment]
Woot woot!
