### ISSUE TITLE
[FEATURE] - Add Windows Repair Tools

### ISSUE THREAD

**Issue by TheDeadGPU** [eliweitzman/EnterpriseTechTool#95]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add SFC /SCANNOW and DISM /Online /Cleanup-Image /RestoreHealth as toolbox functions

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by eliweitzman** [comment]
This looks like it went in in https://github.com/eliweitzman/EnterpriseTechTool/commit/f63f457b91bf51b0051c5afb0c5e757bd3817c0a

Going to conduct some testing to verify

**Comment by eliweitzman** [comment]
Looks like both went in without an issue. UAC elevation was integrated and it appears to be performing as expected
